[env:amour-k08]
platform = espressif32
board = amour-k08-n16r8
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; extra_scripts =
; 	misc/merge.py

lib_deps =
	https://gitee.com/piolib/ESP32-audioI2S.git#3.0.8
    adafruit/Adafruit NeoPixel @ ^1.12.3
	adafruit/Adafruit AHTX0 @ ^2.0.5
	lovyan03/LovyanGFX @ ^1.1.16
	mathertel/OneButton @ ^2.5.0

build_flags = 
	-mfix-esp32-psram-cache-issue

; upload_protocol = espota
; upload_port = 192.168.43.40
